### ISSUE TITLE
Show name of RSS feed (under title)

### ISSUE THREAD

**Issue by leschek** [zakius/Smart-RSS#94] opened 2020-03-03 10:42 UTC
I just discovered this Firefox extension and start testing it. It seems nice, but I would like to ask if is possible to add name of feed (channel) somewhere near the title of an article. When I read all feeds I would like to know at the first sight which title belongs to which feed.

I use Smart RSS 2.8.1 on Firefox 73.0.1

**Comment by zakius** [comment] 2020-03-03 12:13
Do you mean somewhere on the content pane?

**Comment by leschek** [comment] 2020-03-03 12:51
Well,  it would be nice to have it on content pane, but I guess it is more important on that middle pane, where the titles are. I can see the names of authors there and personally I would prefer to have there channel name instead of authors. But some people may prefer author's names, so I guess it would be best make options in settings...

**Comment by zakius** [comment] 2020-03-03 13:04
I see, you mean when multiple sources are selected

that's duplicate of #66 then so I'm closing it, l'll post updates and questions (if any) in that issue

**Closed by zakius** 2020-03-03 13:04 UTC
Labels: question
