### ISSUE TITLE
Problem with changing the appearance of the panels and the list of news

### ISSUE THREAD

**Issue by STATiK2** [zakius/Smart-RSS#96] opened 2020-03-06 07:32 UTC
I use the extension in Opera (67.0.3575.53). Until recently, everything was fine. Perhaps the problem appeared after the latest browser updates.
The essence of the problem is the incorrect operation of switching the type of panels from vertical to horizontal. After updating the extension page with the Refresh button, the panel view is reset to Vertical.
In the horizontal view of the panels, it is impossible to drag the border of the bottom panel ("full news text"). In addition, news headlines are now tightly limited by the width of the screen (not free width as it was before). Therefore, the width of the lines of news headlines has become twice as wide. than it was before.

PS Sorry for my english (google translated).

**Comment by zakius** [comment] 2020-03-06 07:57
I can confirm that some settings are not applied when refreshing the page (it is not initialized properly then)

I can also confirm that it's impossible to resize second and third panel when they are on top of each other and will look into that

I doubt any of these could be caused by browser update

Unfortunately I don't know what you mean with the third issue, I'm sorry. Could you try rephrasing it maybe?

**Comment by STATiK2** [comment] 2020-03-06 08:26
I can better explain on screensots ))

1-st - Erinome RSS (good alternative for subj but I prefer Your fork ^_^ )
2-nd - subj
![1](https://user-images.githubusercontent.com/61863213/76065734-3f04ba00-5f9d-11ea-99b7-2b86d6ba6a04.jpg)
![2](https://user-images.githubusercontent.com/61863213/76065745-45933180-5f9d-11ea-887b-f3a0f324778e.jpg)

**Comment by zakius** [comment] 2020-03-06 09:42
okay, you meant that height of rows could be smaller

I'll take a look, should be able to apply media queries for that probably

**Comment by STATiK2** [comment] 2020-03-06 17:12
Дб
Б......,...,о,.,бббббоооожжжеееее бббббоооожжжеееее п..
--
. куб жл
Ьуб. юддMail.Ru для Android пятница, 06 марта 2020г., 10:57 +0300 от zakius  notifications@github.com :

**Comment by dlechowski** [comment] 2020-03-09 21:50
+1 to STATiK2's issues. 
Can't save changing view settings from vertical to horizontal. 
"Compact" horizontal view is also gone.
Looks like these bugs appeared after recent extension updates - I have the same experience in Opera (chrome ext.) and Firefox. 

Thanks in advance!

**Comment by zakius** [comment] 2020-03-09 22:03
Everything except compact view is fixed in Master, will attempt to fix it too before releasing another package (as CWS releases take some time to get accepted)

**Comment by zakius** [comment] 2020-03-15 15:26
Added optional single line view in last commit, it's possible to choose in options
Closing this now but I'll let you know when I publish the new version

**Closed by zakius** 2020-03-15 15:26 UTC
Labels: bug

**Comment by dlechowski** [comment] 2020-03-22 11:45
Thanks! It looks much better now. 

Just a minor thing though. When the article's title is too long all columns are getting wrap up and put to the next line. Then You can end up with few articles in two lines and others in one - it's not consistent then. You can see that case in the screen below.
I believe that previously, title was just cut off with three dots at the end and whole article was always locked in one line. 

[![Screenshot_11](https://user-images.githubusercontent.com/61993735/77248486-053ce000-6c3a-11ea-9d7b-821dd0c695bd.png)](url)

**Comment by zakius** [comment] 2020-03-22 12:02
I'll look into this

**Comment by zakius** [comment] 2020-03-22 12:58
Okay, that should do it, it'll be fixed in next release.
Just make sure to have `Show full headlines` disabled as it doesn't play well together

**Comment by dlechowski** [comment] 2020-03-22 13:10
> Okay, that should do it, it'll be fixed in next release.
> Just make sure to have `Show full headlines` disabled as it doesn't play well together

Sure! 
Thanks, great work :)
