### ISSUE TITLE
questions: refresh, html, icons, css, filter

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#3] opened 2019-02-23 13:49 UTC
1. is there a way to prevent auto-refresh? i subscribe to lots of feeds and sometimes don't want to refresh all groups/folders, or sometimes i just want to view already read stuff without refreshing - please consider an option to disable auto-refresh if there this isn't currently available

2. what HTML elements are displayed? it appears most are filtered, even images, with no control over what is filtered

3. it appears the reader does not cache favicons? i'm seeing network requests for icons every time the reader is refreshed

4. appears there's a little issue with the CSS - in my case i have a 17 in. 1080p display (1920px H) and fonts are always way too small, however if i increase the UI font size, or set 'layout.css.devPixelsPerPx' to a larger value (1.2), the UI no longer fits the display and there is a H-scroll bar

5. would be very handy to be able to run at least article titles through a filter and display the matches in a "filtered" category, similar to the "pinned" category

i like the overall simplicity of the reader and especially the traditional 3-pane layout (folders on left and titles/articles stack on right)

be happy to open separate issues for each item you may want to address

**Comment by zakius** [comment] 2019-02-24 16:28
1. Currently there is no option to globally disable auto refresh or to modify the default value, it is possible to adjust this per source. I plan to add global settings too.

2. currently textContent property is used to load article content, it indeed filters out all formatting, Definitely should get adjusted, probably I'll add alternative views (current one, *as provided in feed* and mozilla/readability)

3. That's right, favicons are not cached. I definitely would like to do something about them, but I still have to figure out the correct approach to invalidating cache

4. this one will probably take a lot of time as CSS is my weakness but I'll see what I can do

5. could you provide more detail? currently there is search field available looking up in titles of articles of all selected sources (works for a singe source, group or all sources currently, it is possible to select multiple sources but articles are displayed only from the first one, I'll either make it possible to list articles from few sources at once or disable multi selection of sources for clarity)

Thanks for your feedback, I'll create separate issues for 1-4 and would be grateful if you created one for 5 with additional details

**Comment by zakius** [comment] 2019-02-24 17:31
@atomGit can you provide additional information about 4? I cannot reproduce this, what is your browser and it's version?

and about 2 to be precise: textContent strips all tags unless content is CDATA section, in that case it provides complete contents, this will take me more time to figure out than I thought

**Comment by atomGit** [comment] 2019-02-24 18:55
> 1. Currently there is no option to globally disable auto refresh [...] EDIT: there is always at least one root group so you can use that group as global setting if you wish

there's a root group "all feeds", but there's no "properties" context menu item for that group so i'm not seeing how one can set a refresh interval globally - not a problem though since you plan to add a global option in setings

> 2. currently textContent property is used to load article content, it indeed filters out all formatting, Definitely should get adjusted, probably I'll add alternative views (current one, _as provided in feed_ and mozilla/readability)

...or just allow the user to specify what html is allowed instead of hard-coding it - maybe less work? dunno - personally i'd want to allow <img> but block pretty much everything else

> can you provide me addresses of some feeds that get stripped like that? I cannot find any feeds with issue like this on my list

i assume you're referring to html getting stripped - if that's the case, nearly every article in the RT feed contains images at least if that's what you wanted to test...

`https://www.rt.com/rss/`

> can you provide additional information about 4? I cannot reproduce this, what is your browser and it's version?

odd - i just tested again with a vanilla test profile for Firefox 65.0.1 - if i set, for example, the UI font size too large (120% in my case), the reader UI no longer fits horizontally in my display - there is an H-scroll bar - try testing with a larger value perhaps? or maybe try widening the feed list side-bar in addition (drag to resize) - also i tested using the 3-pane layout, not the default, so the feeds are on the left, titles on top-right and article content bottom-right

i can fool with CSS and fix it likely, but it may be pointless to incorporate a solution if you aren't able to reproduce, though it seems odd this would only occur on my system

the other way to produce the same result is to set 'layout.css.devPixelsPerPx' too high

**Comment by zakius** [comment] 2019-02-24 19:47
1. right, it was my mistake: if there is a group selected or any item in that group then feed gets added to that group, but you can also have feeds on the top level and these can't have common settings

I'll add global settings to that + there is need for better management (moving items between groups etc.)

2. that's odd, for me it displays the picture properly, please note that this feed contains only summaries so a single picture + short piece of text, not a whole article, so I can't read that data from feed (I'll add mozilla/readability view later that will fetch whole article from website before parsing for cases like this + add per source + global preferred view)

4. I still cannot reproduce it by changing extension settings but setting layout.css.devPixelsPerPx to high enough value produces this effect

I do all my tests in latest Waterfox and Nightly (unless issue is specific to another browser)

**Comment by atomGit** [comment] 2019-02-24 19:58
re point 2 - well WTH? yes, images do display :) sorry, must've been a particular feed which they didn't perhaps - will let you know if/when i see that issue arise again

layout.css.devPixelsPerPx will produce all sorts of weirdness if you go too high (i think this occurs close to a value of 3 or so) so i wouldn't put a lot of stock in that if you tested with a very large value

i'd say ignore it and see if others complain - if so, i can likely fix the css

i don't know your reasoning for using Waterfox, but if it's a privacy thing, keep an eye on the [Librefox](https://github.com/intika/Librefox) project - not technically a fork, so they keep up with patches/security, which is a problem with WF or any other fork - and if it is privacy/sanity you're shooting for, see [here](https://12bytes.org/articles/tech/firefox)

thanks! and looking forward to your fixes/enhancements - i'm currently using Feedbro and am looking to switch

**Comment by zakius** [comment] 2019-02-24 20:09
I'm using Waterfox for Pocket (old extension) Newsfox (but it's slow so I decided to finally do something about it) and Fire Gestures (current API doesn't allow gestures to work properly)

Feedbro is quite nice but I had some issues with it and been unable to get in touch with devs so I picked up this project, I'm not sure how much work I'll invest here as it's heavily legacy and slow at times, but I'll fix the most burning issues for sure

**Comment by atomGit** [comment] 2019-02-25 10:06
Newsfox is what i used to use as well and i've been looking for a suitable replacement ever since - Feedbro comes close, but as you've discovered there's issues both with it and the developer who refuses, for whatever reason, to post the code on a suitable repo and that bothers me

from all the readers i've tested, yours comes the closest to what i'm looking for

**Comment by zakius** [comment] 2019-02-25 11:44
@atomGit take a look at #7 
I can't upload new version to AMO today due to planned maintenance but feel free to test from source if you want and tell me if anything is wrong

**Comment by atomGit** [comment] 2019-02-25 15:26
i'm a dummy - don't know how to build from source :) - no hurry though - i'll wait for a release

**Comment by zakius** [comment] 2019-02-26 12:56
new version should be available in AMO now

**Comment by atomGit** [comment] 2019-02-26 13:25
this is good! the css needs a little tweaking and a dark theme would be super - i can do the dark theme

on the settings page there's a fixed logo div that covers the option descriptions - see: https://i.imgtc.com/dcM3jmX.png

i can maybe fix that if you tell me where it's supposed to be positioned

**Comment by zakius** [comment] 2019-02-26 15:48
it was supposed to be positioned like [this](https://i.imgur.com/ZCt064l.png) but Gecko renders it slightly off, thanks for your input and will to help!

I'll probably release another patch today or tomorrow addressing not working hotkeys

**Comment by atomGit** [comment] 2019-02-26 20:09
great - did you want me to do a dark theme? i'll be doing one anyway for myself

regarding the h-scroll bar and the reader not fitting within the browser display, i poked around quite a while and was unable to produce a fix - perhaps i will stumble upon the issue while building a dark theme

**Comment by zakius** [comment] 2019-03-09 15:46
@atomGit do you have any progress with dark theme or scaling issues?

**Comment by atomGit** [comment] 2019-03-09 16:43
i have not - no time at the moment

**Comment by zakius** [comment] 2019-03-09 17:57
in the meantime I managed to fix some display issues but don't know yet if it affects scaling

for dark theme I'll refactor stylesheet to make use of custom properties and possibly reduce number of colors used for simplicity, hopefully that will make theming a piece of cake

**Comment by zakius** [comment] 2020-02-16 17:39
is there any issue left of these listed here? if there are any and they still bother you may I ask you to open separate issues for them?

**Closed by zakius** 2020-02-16 17:39 UTC
Labels: question

**Comment by atomGit** [comment] 2020-02-16 17:51
no sir - i think that wraps it up
